// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBx8EL9rW-F_oe-4hvyestK9Vzl_b8590',
    appId: '1:93080016976:web:a8c3824f273a805508d955',
    messagingSenderId: '93080016976',
    projectId: 'bump-57bb6',
    authDomain: 'bump-57bb6.firebaseapp.com',
    storageBucket: 'bump-57bb6.firebasestorage.app',
    measurementId: 'G-CSPKCZZW2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfko_7VvP-cF5B6iRDYo1jyCqAwcZys4k',
    appId: '1:93080016976:android:c6a6074e89c4eab408d955',
    messagingSenderId: '93080016976',
    projectId: 'bump-57bb6',
    storageBucket: 'bump-57bb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_qmvBYjmuKTnyynMJHjqkqIbRjyiI3Y',
    appId: '1:93080016976:ios:f8b4a24a4084361e08d955',
    messagingSenderId: '93080016976',
    projectId: 'bump-57bb6',
    storageBucket: 'bump-57bb6.firebasestorage.app',
    iosBundleId: 'com.evan.bump',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP_qmvBYjmuKTnyynMJHjqkqIbRjyiI3Y',
    appId: '1:93080016976:ios:e2bfe4429e4b728808d955',
    messagingSenderId: '93080016976',
    projectId: 'bump-57bb6',
    storageBucket: 'bump-57bb6.firebasestorage.app',
    iosBundleId: 'com.example.bump',
  );

}